---
title: "Untitled"
output: html_document
date: "2025-04-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r }
# Load required libraries
library(sf)          # For spatial data handling
library(ggplot2)     # For visualization
```

## read ev.geojson

```{r pressure, echo=FALSE}
# Read the GeoJSON file (replace 'your_data_file.geojson' with your actual file)
#ev_stations <- st_read("D:\\AAMatej\\AA-MATEJ-8-2024-SEMESTAR\\436-Statistical Data Visualization\\436- OD TEKOVNI PREDAVANJA\\HW\\HW4\\ev.geojson")
library(sf)

# Correctly formatted URL
url <- "https://raw.githubusercontent.com/krisrs1128/stat436_s25/main/data/ev.geojson"

# Read the GeoJSON data
ev_stations <- st_read(url)

# Print summary of the data
summary(ev_stations)
#ev_stations

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
# Check the structure of the data
glimpse(ev_stations)
```

```{r}
# Visualize the EV charging stations
ggplot(data = ev_stations) +
  geom_sf(aes(color = FUEL_TYPE_), size = 1) +  # Use fuel type for color differentiation
  theme_minimal() +
  labs(
    title = "Wisconsin EV Charging Stations",
    subtitle = "Visualized by Fuel Type",
    color = "Fuel Type"
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "right"
  )
```



```{r}
#install.packages("osmdata")
library(osmdata)
library(sf)
library(ggplot2)

wi_ev <- opq("Wisconsin") %>%
  add_osm_feature(key = "amenity", value = "charging_station") %>%
  osmdata_sf()
wi_ev
ggplot(data = wi_ev$osm_points) +
  geom_sf(color = "green", size = 1) +
  ggtitle("EV Charging Stations in Wisconsin") +
  theme_minimal()
```





